### ISSUE TITLE
More spoof modules?

### ISSUE THREAD

**Issue by Doglover5749TY** [Indirecta-Technologies/olssa#1]
I've been using olssa for a while and I've only had access to the parcel spoof module and I'm hoping to see if there are any other modules we can use or ones that can be pre-enabled that come with olssa without having to manually code them each time.

**Comment by LolloDev5123** [comment]
Hi, OLSSA is a general inspection utility intended for malicious obfuscated scripts, and is not preconfigured or going to be preconfigured to bypass licensing systems like Parcel or Vendr.
